# Generated by Django 4.1.5 on 2023-03-24 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_alter_weather_temperature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='city',
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
